# Generated by Django 5.0.3 on 2024-04-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ptype', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('origin', models.CharField(max_length=100)),
            ],
        ),
    ]
