# Generated by Django 5.0.3 on 2024-04-03 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_plantain_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantain',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
                ('directions', models.TextField()),
                ('serving', models.IntegerField()),
                ('plntype', models.CharField(choices=[('C', 'Cooking Plantains'), ('S', 'Sweet Plantains'), ('G', 'Green Plantains'), ('R', 'Ripe Plantains')], default='C', max_length=1)),
                ('plantain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='main_app.plantain')),
            ],
        ),
    ]
