# Generated by Django 5.0.3 on 2024-04-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_plantain_image_url_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='plantain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plantain'),
        ),
    ]
