# Generated by Django 5.0.3 on 2024-04-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_drink'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantain',
            name='drinks',
            field=models.ManyToManyField(to='main_app.drink'),
        ),
    ]
